###remote
GET http://have-drivers.herokuapp.com/driver/active_drivers?lat= 26.176670&lng=78.008072 HTTP/1.1



Http











###local
GET http://localhost:8000/driver/active_drivers?lat= 26.176670&lng=78.008072 HTTP/1.1


    
### fare calculation

GET http://localhost:8000/driver/rides/ HTTP/1.1
Content-Type: application/json

### create ride

POST http://localhost:8000/driver/rides/ HTTP/1.1
Content-Type: application/json

{
    "customer_id":2,
    "status":3,
    "dest_latitude":"22.7022",
    "dest_longitude":"78.78002",
    "origin_latitude":"22.2322",
    "origin_longitude":"78.78332",
    "origin_string":"56, Suresh Nagar",
    "dest_string":"78, New Colony",
    "driver_id":3,
    "fare":250
}



### create ride

PUT  http://localhost:8000/driver/rides/ HTTP/1.1
Content-Type: application/json

{
    "id":2,
    "status":5
}

### Get driver earnings
GET http://localhost:8000/driver/earnings/?driver=3 HTTP/1.1

4
### ride details
GET http://localhost:8000/driver/history/?identifier=3&by=customer HTTP/1.1
