# Generated by Django 2.2.1 on 2019-06-02 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='image',
        ),
    ]
