# Generated by Django 2.2.1 on 2019-06-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_auto_20190618_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.BigIntegerField()),
                ('status', models.IntegerField()),
                ('dest_latitude', models.FloatField()),
                ('dest_logitude', models.FloatField()),
                ('origin_latitude', models.FloatField()),
                ('origin_longitude', models.FloatField()),
                ('origin_string', models.CharField(max_length=100)),
                ('dest_string', models.CharField(max_length=100)),
                ('driver_id', models.IntegerField()),
            ],
        ),
    ]
