# Generated by Django 2.2.1 on 2019-06-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0007_auto_20190628_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activelogin',
            old_name='userId',
            new_name='user_Id',
        ),
    ]
