# Generated by Django 2.2.1 on 2019-06-30 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0010_auto_20190628_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activelogin',
            name='username',
            field=models.ForeignKey(default='bhole', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', unique=True),
        ),
    ]
