# Generated by Django 2.2.1 on 2019-07-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0011_auto_20190629_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='activelogin',
            name='status',
            field=models.CharField(default='available', max_length=40),
        ),
        migrations.AddField(
            model_name='ride',
            name='fare',
            field=models.FloatField(default=0.0, max_length=5),
        ),
    ]
