# Generated by Django 2.2.1 on 2019-06-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0011_auto_20190629_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activelogin',
            name='location',
        ),
        migrations.AddField(
            model_name='activelogin',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='activelogin',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
