# Generated by Django 2.2.1 on 2019-07-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0012_auto_20190701_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='workers',
            field=models.IntegerField(default=1, max_length=2),
        ),
    ]
