# Generated by Django 2.2.1 on 2019-07-01 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0014_auto_20190701_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activelogin',
            name='username',
            field=models.ForeignKey(default='bhole', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', unique=True),
        ),
    ]
