# Generated by Django 2.2.1 on 2019-07-03 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0012_auto_20190630_0914'),
        ('driver', '0016_appsetting'),
    ]

    operations = [
    ]
