# Generated by Django 2.2.1 on 2019-07-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0020_auto_20190704_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='driver_id',
        ),
        migrations.AddField(
            model_name='ride',
            name='driver_id',
            field=models.IntegerField(default=3),
        ),
    ]
