# Generated by Django 2.2.1 on 2019-07-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0022_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='extra',
            field=models.CharField(default='NULL', max_length=245),
        ),
        migrations.AddField(
            model_name='ride',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
