# Generated by Django 2.2.1 on 2019-10-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0025_ride_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='vehicle_type',
            field=models.CharField(default='Open', max_length=255),
        ),
    ]
